addr: 127.0.0.1:8080
# choose ("mem","redis")
cache_type: redis
# jwt_secret
jwt_secret: "abs_admin"
# jwt to the exp (in seconds)  default 30 minutes
jwt_exp : 1800
# Jwt refresh seconds (default 10 minutes)
jwt_refresh_token : 600
# Login failure rejection policy
login_fail_retry: 3
# Wait time (seconds) for login after failure
login_fail_retry_wait_sec: 30
# removed trash after days, default 30 days
trash_recycle_days: 30
#/ format datetime.['YYYY-MM-DD hh:mm:ss.000000', 'YYYY-MM-DD hh:mm:ss']
datetime_format: "YYYY-MM-DD hh:mm:ss"
# white_list_api
white_list_api: ["/","/admin/sys_login","/admin/captcha"]

db:
  #url: mysql:#root:789@192.168.1.199:3306/hello
  url: mysql:#root:789789@172.17.99.45:3306/axum_admin
  max_connections: 5
  min_connections: 1
  connect_timeout: 60

redis:
  # url: redis:#user:pwd@host:port/db
  url: redis:#:789789@172.17.99.45:6379/